import { useState } from 'react';
import { Activity, ArrowRight, Check, ShieldCheck, TrendingUp, Users } from 'lucide-react';
import { useApp } from '../store/AppContext';
import { Athlete } from '../types';

export function Onboarding(){
 const {addAthlete}=useApp();
 const [step,setStep]=useState(0);
 const [athlete,setAthlete]=useState<Omit<Athlete,'id'|'initials'>>({name:'',position:'',birthYear:2004,height:180,dominantFoot:'Right',color:'#b7f34a'});
 const finish=()=>{if(!athlete.name.trim()||!athlete.position.trim())return;const initials=athlete.name.trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();addAthlete({...athlete,name:athlete.name.trim(),position:athlete.position.trim(),id:crypto.randomUUID(),initials})};
 return <main className="onboarding"><div className="onboard-brand"><span className="brandmark"><Activity/></span><div>TOUCH<span>LINE</span><small>PERFORMANCE LAB</small></div></div><div className="onboard-card">{step===0?<><span className="pill">YOUR FOOTBALL JOURNEY, MEASURED</span><h1>Welcome to your<br/><em>performance lab.</em></h1><p>Build real evidence of your development with consistent weekly testing—not guesses.</p><div className="welcome-features"><div><TrendingUp/><span><b>See real progress</b>Follow every physical quality over time.</span></div><div><Users/><span><b>Grow the squad</b>Add your brother and other athletes anytime.</span></div><div><ShieldCheck/><span><b>Private on your device</b>Your measurements stay in this browser.</span></div></div><button className="primary full" onClick={()=>setStep(1)}>Create first athlete <ArrowRight/></button></>:<><span className="eyebrow">STEP 1 · FIRST ATHLETE</span><h1>Who are we<br/><em>building?</em></h1><p>Start with yourself. You can add your brother immediately afterward.</p><div className="form-grid onboard-form"><label>Full name<input autoFocus value={athlete.name} onChange={e=>setAthlete({...athlete,name:e.target.value})} placeholder="e.g. Ayoub Belkich"/></label><label>Football position<input value={athlete.position} onChange={e=>setAthlete({...athlete,position:e.target.value})} placeholder="e.g. Right back"/></label><label>Birth year<input type="number" min="1950" max={new Date().getFullYear()} value={athlete.birthYear} onChange={e=>setAthlete({...athlete,birthYear:+e.target.value})}/></label><label>Height (cm)<input type="number" min="100" max="230" value={athlete.height} onChange={e=>setAthlete({...athlete,height:+e.target.value})}/></label><label>Dominant foot<select value={athlete.dominantFoot} onChange={e=>setAthlete({...athlete,dominantFoot:e.target.value as Athlete['dominantFoot']})}><option>Right</option><option>Left</option><option>Both</option></select></label><label>Profile colour<input type="color" value={athlete.color} onChange={e=>setAthlete({...athlete,color:e.target.value})}/></label></div><button className="primary full" disabled={!athlete.name.trim()||!athlete.position.trim()} onClick={finish}><Check/> Enter performance lab</button><button className="onboard-back" onClick={()=>setStep(0)}>Back</button></>}</div><span className="onboard-foot">CONSISTENCY OVER INTENSITY · QUALITY OVER EGO</span></main>
}
